#!/usr/bin/env node
/**
 * screen-map viewer 生成器 — 把 docs/screen-map/ 下的所有 capture 版本
 * 索引成 captures.js（file:// 下 fetch 不可用，改用 <script> 注入数据），
 * 并确保 index.html（静态 viewer，见 viewer-template.html）就位。
 *
 * 用法：node tools/screen-map/build-viewer.mjs
 * 每次 sweep 后运行；viewer 打开方式：open docs/screen-map/index.html
 */
import { copyFileSync, existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "..", "..");
const mapDir = path.join(repo, "docs/screen-map");

const captures = [];
for (const entry of readdirSync(mapDir)) {
  const dir = path.join(mapDir, entry);
  if (!statSync(dir).isDirectory()) continue;
  const manifest = path.join(dir, "screens.json");
  if (!existsSync(manifest)) continue;
  const data = JSON.parse(readFileSync(manifest, "utf8"));
  captures.push({ id: entry, ...data });
}
captures.sort((a, b) => (a.capturedAt < b.capturedAt ? 1 : -1));

writeFileSync(
  path.join(mapDir, "captures.js"),
  `// generated by tools/screen-map/build-viewer.mjs — do not edit\nwindow.SCREEN_MAP_CAPTURES = ${JSON.stringify(captures, null, 2)};\n`
);
copyFileSync(path.join(here, "viewer-template.html"), path.join(mapDir, "index.html"));
console.log(`viewer ready: ${captures.length} capture(s) → docs/screen-map/index.html`);
